simulator:
  name: Simulator Earthquake
  description: Simulator Earthquake.
  fields:
    entity_id:
      name: Entity
      example: "sensor.trem_202_notification"
      required: true
      selector:
        entity:
          integration: trem
          domain: sensor
    earthquake_data:
      required: true
      name: Earthquake Data
      description: Earthquake Data for test
      example: '{"author":"cwa","id":"1191299","serial":1,"status":0,"final":0,"eq":{"time":1713779575000,"lon":121.56,"lat":23.78,"depth":10,"mag":7,"loc":"花蓮縣壽豐鄉","max":6},"time":1713779593000}'
      selector:
        text:

save:
  name: Save current image
  description: Save the current image to a path
  fields:
    entity_id:
      name: Entity
      description: Identifier of the image entity.
      example: "image.trem_202_isoseismal_map"
      required: true
      selector:
        entity:
          integration: trem
          domain: image
    filename:
      required: true
      name: Filename
      description: Target filename.
      example: "/tmp/snapshot_{{ entity_id.name }}.png"
      selector:
        text:

update_location:
  name: Update location
  description: Fetch DPIP client location of the entity.
  fields:
    entity_id:
      name: Entity
      example: "sensor.trem_202_notification"
      required: true
      selector:
        entity:
          integration: trem
          domain: sensor
